// Email-based Detection

event.dataset : "email" and
event.action : "received" and
email.attachments.file.extension : (
  "hta" or "js" or "jse" or "vbs" or "ps1" or "psm1" or
  "exe" or "dll" or "scr" or "bat" or "lnk" or
  "zip" or "rar" or "7z" or "iso" or
  "docm" or "xlsm" or "pptm" or "rtf"
) and
email.attachments.count >= 1 and
email.direction : "inbound" and
not email.from.domain : (
  "yourcompany.com",
  "trustedvendor.com"
) and                                           // Tune it for reduce false positive [by domains]
not email.subject : ("newsletter" or "report")  // Tune it for reduce false positive [by subject]


//  Process- Based Detection

process.parent.name: ("WINWORD.EXE", "EXCEL.EXE", "POWERPNT.EXE") and
process.name: ("powershell.exe", "cmd.exe", "wscript.exe", "cscript.exe")
